### ISSUE TITLE
In an experiment where a resultsfile path is already set, pressing stop during the playing of a stimulus crashes apex.

### ISSUE THREAD

**Issue by Gundersanne** [exporl/apex3#186]
'''

#0  QScopedPointer<apex::Feedback, QScopedPointerDeleter<apex::Feedback> >::data (this=0x520)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h:135
#1  0x00007ffff7a56c10 in apex::ExperimentRunDelegate::modFeedback (this=0xf7a660)
    at runner/experimentrundelegate.cpp:753
#2  0x00007ffff7a1a86c in apex::gui::ApexMainWindow::EndFeedBack (this=0x854000) at gui/mainwindow.cpp:335
#3  0x00007ffff798d8ec in apex::ExperimentIo::endFeedback (this=0xf59130) at experimentio.cpp:116
#4  0x00007ffff7ab6ff2 in apex::ExperimentIo::qt_static_metacall (_o=0xf59130, _c=QMetaObject::InvokeMetaMethod, 
    _id=18, _a=0x7fffffffd3f0) at ../../../.build/debug/src/lib/apexmain/moc/moc_experimentio.cpp:238
#5  0x00007ffff5b1dd2a in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff7ab7a25 in apex::ExperimentIo::feedbackDone (this=0xf59130)
    at ../../../.build/debug/src/lib/apexmain/moc/moc_experimentio.cpp:501
#7  0x00007ffff7ab6f41 in apex::ExperimentIo::qt_static_metacall (_o=0xf59130, _c=QMetaObject::InvokeMetaMethod, 
    _id=11, _a=0x7fffffffd600) at ../../../.build/debug/src/lib/apexmain/moc/moc_experimentio.cpp:231
...
'''

Because it's not waiting to ask for a results file, it will crash. 

Option is to disable the stop experiment button while a stimulus is playing.

**Comment by Gundersanne** [comment]
gerrit change 2033
